import os
import json
import queue
import threading
import time
from datetime import datetime
from urllib.parse import urlparse

import requests
from flask import Flask, request, jsonify

# Slippi replay parser
from peppi_py import read_slippi


app = Flask(__name__)

request_queue = queue.Queue()

# ============================================================
# Configuration
# ============================================================

STARTGG_API_URL = "https://api.start.gg/gql/alpha"

STARTGG_BEARER = os.environ["STARTGG_BEARER"]

STARTGG_EVENT_ID = os.environ.get("STARTGG_EVENT_ID")
STARTGG_EVENT_SLUG = os.environ.get("STARTGG_EVENT_SLUG")
STARTGG_URL = os.environ.get("URL")

# ------------------------------------------------------------
# Replay/check-in directory
#
# This should be the SAME directory where your first script
# writes the checkin/checkout/warmup JSON files and SLP files.
# ------------------------------------------------------------

REPLAY_FOLDER = os.environ.get(
    "REPLAY_FOLDER",
    "/web/sharlot/public_html/slp-files"
)

# Scan every minute
SCAN_INTERVAL = 60

# Keep our own state so the same match is never reported twice.
PROCESSED_MATCHES_FILE = os.environ.get(
    "PROCESSED_MATCHES_FILE",
    "processed_matches.json"
)

# ============================================================
# Processed match state
# ============================================================

processed_matches_lock = threading.Lock()


def load_processed_matches():
    if not os.path.exists(PROCESSED_MATCHES_FILE):
        return set()

    try:
        with open(
            PROCESSED_MATCHES_FILE,
            "r",
            encoding="utf-8"
        ) as f:
            data = json.load(f)

        if isinstance(data, list):
            return set(data)

        return set()

    except Exception as e:
        print(
            f"[MATCH SCANNER] Failed to load "
            f"{PROCESSED_MATCHES_FILE}: {e}",
            flush=True
        )

        return set()


processed_matches = load_processed_matches()


def save_processed_matches():
    try:
        with processed_matches_lock:
            data = sorted(processed_matches)

        with open(
            PROCESSED_MATCHES_FILE,
            "w",
            encoding="utf-8"
        ) as f:
            json.dump(data, f, indent=2)

    except Exception as e:
        print(
            f"[MATCH SCANNER] Failed to save processed matches: {e}",
            flush=True
        )


# ============================================================
# Utility functions
# ============================================================

def parse_timestamp(timestamp):
    """
    Parse timestamps generated by your check-in/check-out code.

    Expected:
        20260827T214500

    Also accepts a few common variants.
    """

    if not timestamp:
        return None

    timestamp = str(timestamp).strip()

    formats = [
        "%Y%m%dT%H%M%S",
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%dT%H:%M:%S.%f",
    ]

    for fmt in formats:
        try:
            return datetime.strptime(timestamp, fmt)
        except ValueError:
            pass

    return None


def get_json_timestamp(data, filepath):
    """
    Get timestamp from JSON.

    Falls back to the file modification time.
    """

    timestamp = data.get("timestamp")

    parsed = parse_timestamp(timestamp)

    if parsed:
        return parsed

    try:
        return datetime.fromtimestamp(
            os.path.getmtime(filepath)
        )
    except Exception:
        return None


def get_console_name(data):
    """
    Support both:

        console_name
        consolename
    """

    return (
        data.get("console_name")
        or data.get("consolename")
        or data.get("console")
    )


def get_nickname(data):
    return (
        data.get("nickname")
        or data.get("name")
        or ""
    ).strip()


def get_entrant_id(data):
    value = (
        data.get("eid")
        or data.get("entrantid")
        or data.get("entrant_id")
    )

    if value is None:
        return None

    return str(value)


def get_replay_console_name(filepath):
    """
    Your replay filenames appear to follow:

        something.console_name.slp

    Example:

        Game.Station1.slp
    """

    filename = os.path.basename(filepath)

    parts = filename.rsplit(".", 2)

    if (
        len(parts) == 3
        and parts[2].lower() == "slp"
        and parts[1]
    ):
        return parts[1]

    return None


def get_replay_time(filepath):
    """
    Prefer filesystem creation time if available.

    Fall back to modification time.
    """

    try:
        stat = os.stat(filepath)

        # Linux generally does not expose creation time.
        birthtime = getattr(stat, "st_birthtime", None)

        if birthtime:
            return datetime.fromtimestamp(birthtime)

        return datetime.fromtimestamp(stat.st_mtime)

    except Exception:
        return None


def normalize_name(value):
    if value is None:
        return ""

    return str(value).strip().casefold()


# ============================================================
# Check-in / checkout / warmup scanning
# ============================================================

def scan_session_files():
    """
    Find all checkin, checkout, and warmup JSON files.

    Returns:

        {
            "checkins": [...],
            "checkouts": [...],
            "warmups": [...]
        }
    """

    result = {
        "checkins": [],
        "checkouts": [],
        "warmups": [],
    }

    if not os.path.isdir(REPLAY_FOLDER):
        print(
            f"[MATCH SCANNER] Replay folder does not exist: "
            f"{REPLAY_FOLDER}",
            flush=True
        )
        return result

    for filename in os.listdir(REPLAY_FOLDER):

        if not filename.lower().endswith(".json"):
            continue

        filepath = os.path.join(
            REPLAY_FOLDER,
            filename
        )

        try:
            with open(
                filepath,
                "r",
                encoding="utf-8"
            ) as f:
                data = json.load(f)

        except Exception as e:
            print(
                f"[MATCH SCANNER] Could not read {filepath}: {e}",
                flush=True
            )
            continue

        if not isinstance(data, dict):
            continue

        timestamp = get_json_timestamp(
            data,
            filepath
        )

        if timestamp is None:
            continue

        console_name = get_console_name(data)
        nickname = get_nickname(data)
        entrant_id = get_entrant_id(data)

        if not console_name or not nickname:
            continue

        entry = {
            "filepath": filepath,
            "filename": filename,
            "timestamp": timestamp,
            "console_name": console_name,
            "nickname": nickname,
            "entrant_id": entrant_id,
            "data": data,
        }

        filename_lower = filename.lower()

        if "checkin" in filename_lower:
            result["checkins"].append(entry)

        elif "checkout" in filename_lower:
            result["checkouts"].append(entry)

        elif "warmup" in filename_lower:
            result["warmups"].append(entry)

    result["checkins"].sort(
        key=lambda x: x["timestamp"]
    )

    result["checkouts"].sort(
        key=lambda x: x["timestamp"]
    )

    result["warmups"].sort(
        key=lambda x: x["timestamp"]
    )

    return result


# ============================================================
# Pair check-in -> checkout
# ============================================================

def pair_sessions(checkins, checkouts):
    """
    Pair each check-in with the next chronological checkout
    having the same console + nickname.

    A checkout cannot be reused.
    """

    used_checkouts = set()
    sessions = []

    for checkin in checkins:

        candidates = []

        for checkout_index, checkout in enumerate(
            checkouts
        ):

            if checkout_index in used_checkouts:
                continue

            if normalize_name(
                checkout["console_name"]
            ) != normalize_name(
                checkin["console_name"]
            ):
                continue

            if normalize_name(
                checkout["nickname"]
            ) != normalize_name(
                checkin["nickname"]
            ):
                continue

            if checkout["timestamp"] <= checkin["timestamp"]:
                continue

            candidates.append(
                (
                    checkout["timestamp"],
                    checkout_index,
                    checkout
                )
            )

        if not candidates:
            continue

        candidates.sort(
            key=lambda x: x[0]
        )

        _, checkout_index, checkout = candidates[0]

        used_checkouts.add(checkout_index)

        sessions.append({
            "checkin": checkin,
            "checkout": checkout,
            "console_name": checkin["console_name"],
            "nickname": checkin["nickname"],
            "entrant_id": (
                checkin["entrant_id"]
                or checkout["entrant_id"]
            ),
            "start": checkin["timestamp"],
            "end": checkout["timestamp"],
        })

    return sessions


# ============================================================
# Replay discovery
# ============================================================

def find_replays_for_session(session):
    """
    Find SLP files on the same console whose timestamps fall
    inside the player's check-in -> checkout window.
    """

    results = []

    console_name = normalize_name(
        session["console_name"]
    )

    if not os.path.isdir(REPLAY_FOLDER):
        return results

    for filename in os.listdir(REPLAY_FOLDER):

        if not filename.lower().endswith(".slp"):
            continue

        filepath = os.path.join(
            REPLAY_FOLDER,
            filename
        )

        replay_console = get_replay_console_name(
            filepath
        )

        if not replay_console:
            continue

        if normalize_name(
            replay_console
        ) != console_name:
            continue

        replay_time = get_replay_time(filepath)

        if replay_time is None:
            continue

        if replay_time < session["start"]:
            continue

        if replay_time > session["end"]:
            continue

        results.append({
            "filepath": filepath,
            "filename": filename,
            "timestamp": replay_time,
        })

    results.sort(
        key=lambda x: x["timestamp"]
    )

    return results


# ============================================================
# Replay parsing
# ============================================================

def get_player_nickname(player):
    """
    Try to extract the Slippi player nickname.

    peppi versions differ somewhat, so this deliberately
    checks several possible attributes.
    """

    possible_values = [
        getattr(player, "nametag", None),
        getattr(player, "name", None),
        getattr(player, "nickname", None),
    ]

    for value in possible_values:
        if value:
            return str(value).strip()

    # Some versions expose metadata through a dict-like object.
    try:
        if isinstance(player, dict):
            for key in (
                "nametag",
                "name",
                "nickname",
            ):
                value = player.get(key)
                if value:
                    return str(value).strip()
    except Exception:
        pass

    return None


def extract_replay_result(filepath):
    """
    Read the final game state from an SLP replay.

    Returns:

        {
            "players": [
                {
                    "nickname": ...,
                    "port": ...,
                    "stocks": ...,
                    "percent": ...
                }
            ]
        }

    """

    print(
        f"[MATCH SCANNER] Reading replay: {filepath}",
        flush=True
    )

    game = read_slippi(
        filepath,
        skip_frames=False
    )

    if not hasattr(game, "start"):
        raise RuntimeError(
            "Replay does not contain start data"
        )

    if not hasattr(game.start, "players"):
        raise RuntimeError(
            "Replay does not contain player data"
        )

    if not hasattr(game, "frames"):
        raise RuntimeError(
            "Replay does not contain frame data"
        )

    players = game.start.players

    if not players:
        raise RuntimeError(
            "Replay has no players"
        )

    player_ports = [
        p.port
        for p in players
    ]

    min_port = min(player_ports)

    results = []

    for player in players:

        port_key = (
            0
            if player.port == min_port
            else 1
        )

        stocks = None
        percent = None

        try:
            port_data = game.frames.ports[
                port_key
            ]

            stocks = (
                port_data
                .leader
                .post
                .stocks[-1]
                .as_py()
            )

            percent = (
                port_data
                .leader
                .post
                .percent[-1]
                .as_py()
            )

        except Exception as e:

            print(
                f"[MATCH SCANNER] Could not read "
                f"final state for port {player.port}: {e}",
                flush=True
            )

        nickname = get_player_nickname(
            player
        )

        results.append({
            "nickname": nickname,
            "port": player.port,
            "stocks": stocks,
            "percent": percent,
        })

    return {
        "players": results
    }


# ============================================================
# Match player identification
# ============================================================

def identify_match_players(
    replay_result,
    session1,
    session2
):
    """
    Determine which replay player belongs to each session.

    First tries to match Slippi nametags.

    If names aren't available, falls back to port order.

    This fallback is only safe if your check-in system
    consistently assigns the players to P1/P2.
    """

    replay_players = replay_result["players"]

    nickname1 = normalize_name(
        session1["nickname"]
    )

    nickname2 = normalize_name(
        session2["nickname"]
    )

    # --------------------------------------------------------
    # Best case: Slippi exposes player nicknames.
    # --------------------------------------------------------

    if all(
        player.get("nickname")
        for player in replay_players
    ):

        for p1 in replay_players:

            for p2 in replay_players:

                if p1 is p2:
                    continue

                if (
                    normalize_name(
                        p1["nickname"]
                    ) == nickname1
                    and
                    normalize_name(
                        p2["nickname"]
                    ) == nickname2
                ):

                    return p1, p2

    # --------------------------------------------------------
    # Fallback: sort by port.
    # --------------------------------------------------------

    replay_players = sorted(
        replay_players,
        key=lambda x: x["port"]
    )

    if len(replay_players) >= 2:

        return (
            replay_players[0],
            replay_players[1],
        )

    return None, None


# ============================================================
# Determine winner
# ============================================================

def determine_winner(
    player1,
    player2
):
    """
    Winner rules:

    1. More stocks wins.
    2. If stocks are tied, lower percent wins.
    """

    stocks1 = player1.get("stocks")
    stocks2 = player2.get("stocks")

    percent1 = player1.get("percent")
    percent2 = player2.get("percent")

    if stocks1 is None or stocks2 is None:
        raise RuntimeError(
            "Could not determine final stock counts"
        )

    # --------------------------------------------------------
    # Stocks determine the winner.
    # --------------------------------------------------------

    if stocks1 > stocks2:
        return 1

    if stocks2 > stocks1:
        return 2

    # --------------------------------------------------------
    # Stocks tied.
    #
    # Lowest percent wins.
    # --------------------------------------------------------

    if percent1 is None or percent2 is None:
        raise RuntimeError(
            "Stocks were tied but final percent "
            "could not be determined"
        )

    if percent1 < percent2:
        return 1

    if percent2 < percent1:
        return 2

    # --------------------------------------------------------
    # Completely tied.
    # --------------------------------------------------------

    return 0


# ============================================================
# Match ID
# ============================================================

def make_match_key(
    replay,
    session1,
    session2
):
    """
    Generate a stable ID so the same replay isn't reported
    repeatedly every 60 seconds.
    """

    players = sorted([
        (
            normalize_name(session1["nickname"]),
            str(
                session1.get("entrant_id")
                or ""
            )
        ),
        (
            normalize_name(session2["nickname"]),
            str(
                session2.get("entrant_id")
                or ""
            )
        ),
    ])

    return "|".join([
        os.path.abspath(
            replay["filepath"]
        ),
        players[0][0],
        players[0][1],
        players[1][0],
        players[1][1],
    ])


# ============================================================
# Find overlapping player sessions
# ============================================================

def find_overlapping_sessions(
    sessions
):
    """
    A match requires two different players on the same
    console with overlapping check-in/check-out windows.
    """

    matches = []

    for i in range(len(sessions)):

        session1 = sessions[i]

        for j in range(i + 1, len(sessions)):

            session2 = sessions[j]

            # Must be different players.
            if (
                normalize_name(
                    session1["nickname"]
                )
                ==
                normalize_name(
                    session2["nickname"]
                )
            ):
                continue

            # Must be the same console.
            if (
                normalize_name(
                    session1["console_name"]
                )
                !=
                normalize_name(
                    session2["console_name"]
                )
            ):
                continue

            # ------------------------------------------------
            # Check whether their sessions overlap.
            # ------------------------------------------------

            overlap_start = max(
                session1["start"],
                session2["start"]
            )

            overlap_end = min(
                session1["end"],
                session2["end"]
            )

            if overlap_start >= overlap_end:
                continue

            matches.append({
                "player1": session1,
                "player2": session2,
                "overlap_start": overlap_start,
                "overlap_end": overlap_end,
            })

    return matches


# ============================================================
# Process replay matches
# ============================================================

def process_replay_matches():
    """
    Scan the entire replay/check-in directory and report any
    newly completed matches.
    """

    print(
        "[MATCH SCANNER] Starting scan...",
        flush=True
    )

    files = scan_session_files()

    print(
        "[MATCH SCANNER] Found "
        f"{len(files['checkins'])} check-ins, "
        f"{len(files['checkouts'])} check-outs, "
        f"{len(files['warmups'])} warmups.",
        flush=True
    )

    # Warmups are deliberately collected above but aren't used
    # to report tournament matches. They remain available if
    # you later want warmup-specific logic.

    sessions = pair_sessions(
        files["checkins"],
        files["checkouts"]
    )

    print(
        f"[MATCH SCANNER] Found "
        f"{len(sessions)} completed player sessions.",
        flush=True
    )

    overlapping_matches = find_overlapping_sessions(
        sessions
    )

    print(
        f"[MATCH SCANNER] Found "
        f"{len(overlapping_matches)} possible matches.",
        flush=True
    )

    for possible_match in overlapping_matches:

        session1 = possible_match["player1"]
        session2 = possible_match["player2"]

        # ----------------------------------------------------
        # Find replays for player 1.
        #
        # Because the sessions overlap, the replay must also
        # be inside the overlap period.
        # ----------------------------------------------------

        replay_candidates = find_replays_for_session(
            session1
        )

        for replay in replay_candidates:

            replay_time = replay["timestamp"]

            if replay_time < possible_match["overlap_start"]:
                continue

            if replay_time > possible_match["overlap_end"]:
                continue

            match_key = make_match_key(
                replay,
                session1,
                session2
            )

            with processed_matches_lock:
                already_processed = (
                    match_key
                    in processed_matches
                )

            if already_processed:
                continue

            print(
                "\n[MATCH SCANNER] ============================",
                flush=True
            )

            print(
                f"[MATCH SCANNER] Replay: "
                f"{replay['filename']}",
                flush=True
            )

            print(
                f"[MATCH SCANNER] "
                f"{session1['nickname']} vs "
                f"{session2['nickname']}",
                flush=True
            )

            try:

                # --------------------------------------------
                # Parse replay.
                # --------------------------------------------

                replay_result = extract_replay_result(
                    replay["filepath"]
                )

                replay_p1, replay_p2 = identify_match_players(
                    replay_result,
                    session1,
                    session2
                )

                if replay_p1 is None or replay_p2 is None:
                    raise RuntimeError(
                        "Could not identify both players "
                        "in the replay"
                    )

                # --------------------------------------------
                # Determine winner.
                # --------------------------------------------

                winner = determine_winner(
                    replay_p1,
                    replay_p2
                )

                if winner == 0:
                    print(
                        "[MATCH SCANNER] Match is completely tied. "
                        "No result will be reported.",
                        flush=True
                    )

                    # Mark it processed so we don't repeatedly
                    # print it every minute.
                    with processed_matches_lock:
                        processed_matches.add(
                            match_key
                        )

                    save_processed_matches()

                    continue

                if winner == 1:

                    winner_session = session1
                    loser_session = session2
                    winner_replay = replay_p1
                    loser_replay = replay_p2

                else:

                    winner_session = session2
                    loser_session = session1
                    winner_replay = replay_p2
                    loser_replay = replay_p1

                # --------------------------------------------
                # Log result.
                # --------------------------------------------

                print(
                    "[MATCH SCANNER] RESULT",
                    flush=True
                )

                print(
                    f"[MATCH SCANNER] Winner: "
                    f"{winner_session['nickname']}",
                    flush=True
                )

                print(
                    f"[MATCH SCANNER] "
                    f"Winner stocks: "
                    f"{winner_replay['stocks']}",
                    flush=True
                )

                print(
                    f"[MATCH SCANNER] "
                    f"Winner percent: "
                    f"{winner_replay['percent']}",
                    flush=True
                )

                print(
                    f"[MATCH SCANNER] "
                    f"Loser: "
                    f"{loser_session['nickname']}",
                    flush=True
                )

                print(
                    f"[MATCH SCANNER] "
                    f"Loser stocks: "
                    f"{loser_replay['stocks']}",
                    flush=True
                )

                print(
                    f"[MATCH SCANNER] "
                    f"Loser percent: "
                    f"{loser_replay['percent']}",
                    flush=True
                )

                # --------------------------------------------
                # Report to start.gg.
                # --------------------------------------------

                if (
                    not winner_session.get("entrant_id")
                    or
                    not loser_session.get("entrant_id")
                ):

                    raise RuntimeError(
                        "Missing entrant ID for one or both players"
                    )

                report_result = process_request(
                    winner_session["nickname"],
                    loser_session["nickname"],
                    1,
                    0,
                    winner_session["entrant_id"],
                    loser_session["entrant_id"],
                )

                print(
                    f"[MATCH SCANNER] start.gg result: "
                    f"{report_result}",
                    flush=True
                )

                # --------------------------------------------
                # Mark processed.
                # --------------------------------------------

                with processed_matches_lock:
                    processed_matches.add(
                        match_key
                    )

                save_processed_matches()

            except Exception as e:

                print(
                    f"[MATCH SCANNER] Error processing "
                    f"{replay['filename']}: {e}",
                    flush=True
                )

            print(
                "[MATCH SCANNER] ============================\n",
                flush=True
            )


# ============================================================
# Background scanner
# ============================================================

def replay_scanner_worker():

    print(
        "[MATCH SCANNER] Background scanner started.",
        flush=True
    )

    while True:

        try:
            process_replay_matches()

        except Exception as e:

            print(
                f"[MATCH SCANNER] Scanner error: {e}",
                flush=True
            )

        time.sleep(
            SCAN_INTERVAL
        )


# ============================================================
# start.gg GraphQL helper
# ============================================================

def startgg_request(
    query,
    variables=None
):
    """
    Execute a GraphQL request against start.gg.
    """

    headers = {
        "Authorization": (
            f"Bearer {STARTGG_BEARER}"
        ),
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    payload = {
        "query": query,
        "variables": variables or {},
    }

    response = requests.post(
        STARTGG_API_URL,
        headers=headers,
        json=payload,
        timeout=30,
    )

    response.raise_for_status()

    result = response.json()

    if "errors" in result:

        messages = []

        for error in result["errors"]:

            messages.append(
                error.get(
                    "message",
                    str(error)
                )
            )

        raise RuntimeError(
            "start.gg API error: "
            + "; ".join(messages)
        )

    return result["data"]


# ============================================================
# Event lookup
# ============================================================

def get_event_id_from_slug(slug):

    query = """
    query GetEvent($slug: String!) {
        event(slug: $slug) {
            id
            name
        }
    }
    """

    data = startgg_request(
        query,
        {
            "slug": slug
        }
    )

    event = data.get("event")

    if not event:
        raise RuntimeError(
            f"Could not find start.gg event: {slug}"
        )

    return str(event["id"])


def extract_event_id():

    if STARTGG_EVENT_ID:
        return str(
            STARTGG_EVENT_ID
        )

    if STARTGG_EVENT_SLUG:
        return get_event_id_from_slug(
            STARTGG_EVENT_SLUG
        )

    if STARTGG_URL:

        parsed = urlparse(
            STARTGG_URL
        )

        path_parts = [
            part
            for part in parsed.path.split("/")
            if part
        ]

        if "event" not in path_parts:

            raise RuntimeError(
                "URL must be a start.gg event URL "
                "containing /event/"
            )

        event_index = path_parts.index(
            "event"
        )

        if event_index + 1 >= len(path_parts):

            raise RuntimeError(
                "Could not determine event slug from URL"
            )

        if len(path_parts) < 2:

            raise RuntimeError(
                "Could not determine tournament slug"
            )

        tournament_slug = path_parts[1]

        event_slug = path_parts[
            event_index + 1
        ]

        slug = (
            f"{tournament_slug}/{event_slug}"
        )

        return get_event_id_from_slug(
            slug
        )

    raise RuntimeError(
        "Set one of STARTGG_EVENT_ID, "
        "STARTGG_EVENT_SLUG, or URL"
    )


# ============================================================
# Get sets
# ============================================================

def get_event_sets(event_id):

    all_sets = []

    page = 1
    per_page = 100

    query = """
    query EventSets(
        $eventId: ID!,
        $page: Int!,
        $perPage: Int!
    ) {
        event(id: $eventId) {
            id
            name

            sets(
                page: $page
                perPage: $perPage
                sortType: STANDARD
            ) {
                pageInfo {
                    total
                }

                nodes {
                    id
                    state

                    slots {
                        id

                        entrant {
                            id
                            name
                        }

                        standing {
                            stats {
                                score {
                                    value
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    """

    while True:

        data = startgg_request(
            query,
            {
                "eventId": event_id,
                "page": page,
                "perPage": per_page,
            }
        )

        event = data.get("event")

        if not event:

            raise RuntimeError(
                f"Could not find event {event_id}"
            )

        sets = event["sets"]

        nodes = sets["nodes"]

        all_sets.extend(nodes)

        total = sets["pageInfo"]["total"]

        if len(all_sets) >= total:
            break

        page += 1

    return all_sets


# ============================================================
# Find requested match
# ============================================================

def find_specific_match(
    sets,
    player1,
    player2
):

    player1 = player1.strip()
    player2 = player2.strip()

    for match_index, match in enumerate(
        sets,
        start=1
    ):

        slots = match.get(
            "slots",
            []
        )

        if len(slots) < 2:
            continue

        entrants = []

        for slot in slots:

            entrant = slot.get(
                "entrant"
            )

            if entrant:

                entrants.append({
                    "id": str(
                        entrant["id"]
                    ),
                    "name": entrant["name"],
                    "slot": slot,
                })

        if len(entrants) != 2:
            continue

        found_p1 = entrants[0]["name"].strip()
        found_p2 = entrants[1]["name"].strip()

        if (
            (
                found_p1 == player1
                and
                found_p2 == player2
            )
            or
            (
                found_p1 == player2
                and
                found_p2 == player1
            )
        ):

            return {
                "matchIndex": match_index,
                "set": match,
                "entrant1": entrants[0],
                "entrant2": entrants[1],
            }

    return None


# ============================================================
# Report match
# ============================================================

def report_match(
    match,
    player1,
    player2,
    p1wins,
    p2wins
):

    if not 0 <= p1wins <= 4:
        raise ValueError(
            "p1wins must be between 0 and 4"
        )

    if not 0 <= p2wins <= 4:
        raise ValueError(
            "p2wins must be between 0 and 4"
        )

    if p1wins == p2wins:
        raise ValueError(
            "The match score cannot be tied"
        )

    set_id = str(
        match["set"]["id"]
    )

    entrant1_id = str(
        match["entrant1"]["id"]
    )

    entrant2_id = str(
        match["entrant2"]["id"]
    )

    if (
        match["entrant1"]["name"].strip()
        ==
        player1.strip()
    ):

        player1_entrant_id = entrant1_id
        player2_entrant_id = entrant2_id

    else:

        player1_entrant_id = entrant2_id
        player2_entrant_id = entrant1_id

    if p1wins > p2wins:
        winner_id = player1_entrant_id
    else:
        winner_id = player2_entrant_id

    mutation = """
    mutation ReportSet(
        $setId: ID!,
        $winnerId: ID!
    ) {
        reportBracketSet(
            setId: $setId,
            winnerId: $winnerId
        ) {
            id
            state
        }
    }
    """

    data = startgg_request(
        mutation,
        {
            "setId": set_id,
            "winnerId": winner_id,
        }
    )

    return {
        "setId": set_id,
        "winnerId": winner_id,
        "p1wins": p1wins,
        "p2wins": p2wins,
        "apiResult": data,
    }


# ============================================================
# Process request
# ============================================================

def process_request(
    player1,
    player2,
    p1wins,
    p2wins,
    player1_entrant_id=None,
    player2_entrant_id=None,
):

    event_id = extract_event_id()

    # --------------------------------------------------------
    # Get all sets.
    # --------------------------------------------------------

    sets = get_event_sets(
        event_id
    )

    # --------------------------------------------------------
    # If entrant IDs were supplied, prefer those.
    #
    # This avoids ambiguity when two start.gg entrants have
    # similar names.
    # --------------------------------------------------------

    match = None

    if (
        player1_entrant_id
        and
        player2_entrant_id
    ):

        target_ids = {
            str(player1_entrant_id),
            str(player2_entrant_id),
        }

        for match_index, candidate in enumerate(
            sets,
            start=1
        ):

            slots = candidate.get(
                "slots",
                []
            )

            entrant_ids = set()

            for slot in slots:

                entrant = slot.get(
                    "entrant"
                )

                if entrant:
                    entrant_ids.add(
                        str(
                            entrant["id"]
                        )
                    )

            if target_ids.issubset(
                entrant_ids
            ):

                entrants = []

                for slot in slots:

                    entrant = slot.get(
                        "entrant"
                    )

                    if entrant:

                        entrants.append({
                            "id": str(
                                entrant["id"]
                            ),
                            "name": entrant["name"],
                            "slot": slot,
                        })

                if len(entrants) >= 2:

                    entrant1 = next(
                        (
                            e
                            for e in entrants
                            if e["id"]
                            == str(player1_entrant_id)
                        ),
                        None
                    )

                    entrant2 = next(
                        (
                            e
                            for e in entrants
                            if e["id"]
                            == str(player2_entrant_id)
                        ),
                        None
                    )

                    if entrant1 and entrant2:

                        match = {
                            "matchIndex": match_index,
                            "set": candidate,
                            "entrant1": entrant1,
                            "entrant2": entrant2,
                        }

                        break

    # --------------------------------------------------------
    # Fall back to player names.
    # --------------------------------------------------------

    if match is None:

        match = find_specific_match(
            sets,
            player1,
            player2,
        )

    if match is None:

        raise RuntimeError(
            f"Could not find a match between "
            f"{player1} and {player2}"
        )

    return report_match(
        match,
        player1,
        player2,
        p1wins,
        p2wins,
    )


# ============================================================
# API worker
# ============================================================

def selenium_worker():

    while True:

        job = request_queue.get()

        try:

            result = process_request(
                job["player1"],
                job["player2"],
                job["p1wins"],
                job["p2wins"],
                job.get("player1_entrant_id"),
                job.get("player2_entrant_id"),
            )

            job["result"] = {
                "success": True,
                "result": result,
            }

            job["status"] = 200

        except Exception as e:

            job["result"] = {
                "success": False,
                "response": {
                    "status": 500,
                    "error": str(e)
                }
            }

            job["status"] = 500

        finally:

            job["event"].set()

            request_queue.task_done()


worker_thread = threading.Thread(
    target=selenium_worker,
    daemon=True,
)

worker_thread.start()


# ============================================================
# Flask endpoints
# ============================================================

@app.route(
    "/health",
    methods=["GET"]
)
def health():

    return {
        "status": "ok",
        "service": "meleenium"
    }, 200


@app.route(
    "/find-matches",
    methods=["POST"]
)
def find_matches_endpoint():

    try:

        data = request.get_json()

        if not data:

            raise ValueError(
                "Request body must contain JSON"
            )

        player1 = data["player1"]
        player2 = data["player2"]

        p1wins = int(
            data["p1wins"]
        )

        p2wins = int(
            data["p2wins"]
        )

        job = {
            "player1": player1,
            "player2": player2,
            "p1wins": p1wins,
            "p2wins": p2wins,

            "player1_entrant_id": data.get(
                "player1_entrant_id"
            ),

            "player2_entrant_id": data.get(
                "player2_entrant_id"
            ),

            "event": threading.Event(),
            "result": None,
            "status": None,
        }

        request_queue.put(job)

        job["event"].wait()

        return jsonify(
            job["result"]
        ), job["status"]

    except Exception as e:

        return jsonify({
            "success": False,
            "response": {
                "status": 500,
                "error": str(e)
            }
        }), 500


# ============================================================
# Start
# ============================================================

if __name__ == "__main__":

    # --------------------------------------------------------
    # Start automatic replay scanner.
    # --------------------------------------------------------

    scanner_thread = threading.Thread(
        target=replay_scanner_worker,
        daemon=True,
    )

    scanner_thread.start()

    print(
        "[MATCH SCANNER] Automatic match detection enabled.",
        flush=True
    )

    print(
        f"[MATCH SCANNER] Replay folder: "
        f"{REPLAY_FOLDER}",
        flush=True
    )

    print(
        f"[MATCH SCANNER] Scan interval: "
        f"{SCAN_INTERVAL} seconds",
        flush=True
    )

    # --------------------------------------------------------
    # Start Flask.
    # --------------------------------------------------------

    app.run(
        host="0.0.0.0",
        port=5000,
        threaded=True,
    )

